version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: tododb
      MYSQL_USER: Sudhamshu
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    networks:
      - my_network

  app:
    image: to-do-api
    restart: always
    environment:
      DATABASE_HOST: db
      DATABASE_USER: dockeruser
      DATABASE_PASSWORD: yourpassword
    networks:
      - my_network

networks:
  my_network:
